#
---
- name: Update apt cache
  apt: update_cache=yes

- name: Install required packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-fpm
    - nginx
    - php5-common
    - php5-json

- name: Start php
  service: name=php5-fpm state=started

- name: Start nginx
  service: name=nginx state=started

- name: Delete default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Create default nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/ansible owner=www-data group=www-data
  notify: reload nginx

- copy: src={{ item.src }} dest=/usr/share/nginx/html/{{ item.dest }}
  with_items:
    - { src: 'index.html', dest: 'index.html' }
    - { src: 'info.php', dest: 'info.php' }
    - { src: '502.html', dest: '502.html' }
    - { src: '50x.html', dest: '50x.html' }
    - { src: 'robots.txt', dest: 'robots.txt' }
    - { src: 'nginx_502.png', dest: 'nginx_502.png' }
    - { src: 'nginx.png', dest: 'nginx.png' }

